/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.xmlProject.View;

import com.xmlProject.controller.XMLParcer;
import com.xmlProject.model.Homework;
import com.xmlProject.model.HomeworksArray;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.xml.bind.JAXBException;

/**
 *
 * @author fgg12
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form view
     */
    private  XMLParcer parce;
    HomeworksArray arrayOfHomeworks;
    
    
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        homeworkName = new javax.swing.JTextField();
        task = new javax.swing.JTextField();
        platform = new javax.swing.JTextField();
        endDate = new javax.swing.JTextField();
        hint = new javax.swing.JTextField();
        ButtonNext = new javax.swing.JButton();
        ButtonPrevious = new javax.swing.JButton();
        ButtonSubmit = new javax.swing.JButton();
        ButtonDeleteElement = new javax.swing.JButton();
        ButtonClearFields = new javax.swing.JButton();
        ButtonSave = new javax.swing.JButton();
        ButtonOpen = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("homework name:");

        jLabel2.setText("task:");

        jLabel3.setText("platform:");

        jLabel4.setText("end date:");

        jLabel5.setText("hint");

        platform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platformActionPerformed(evt);
            }
        });

        hint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintActionPerformed(evt);
            }
        });

        ButtonNext.setText("Next");
        ButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonNextActionPerformed(evt);
            }
        });

        ButtonPrevious.setText("Previous");
        ButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPreviousActionPerformed(evt);
            }
        });

        ButtonSubmit.setText("Submit element");
        ButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSubmitActionPerformed(evt);
            }
        });

        ButtonDeleteElement.setText("Delete element");
        ButtonDeleteElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteElementActionPerformed(evt);
            }
        });

        ButtonClearFields.setText("Clear fields");
        ButtonClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClearFieldsActionPerformed(evt);
            }
        });

        ButtonSave.setText("Save");
        ButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSaveActionPerformed(evt);
            }
        });

        ButtonOpen.setText("Open");
        ButtonOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonOpenActionPerformed(evt);
            }
        });

        jLabel6.setVisible(false);
        jLabel6.setForeground(new java.awt.Color(255, 0, 51));
        jLabel6.setText("error loading file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(ButtonPrevious)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ButtonSubmit)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(task, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(platform, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(homeworkName)
                                    .addComponent(endDate)
                                    .addComponent(hint, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonNext))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ButtonDeleteElement)
                                .addGap(29, 29, 29)
                                .addComponent(ButtonClearFields))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(ButtonSave)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(ButtonOpen))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(homeworkName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(task, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(platform, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonNext)
                    .addComponent(ButtonPrevious))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSubmit)
                    .addComponent(ButtonDeleteElement)
                    .addComponent(ButtonClearFields))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSave)
                    .addComponent(ButtonOpen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void platformActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void hintActionPerformed(java.awt.event.ActionEvent evt) {                                     
        // TODO add your handling code here:
    }                                    

    private void ButtonNextActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	Homework temp = new Homework();
    	try{
        	temp = new Homework(arrayOfHomeworks.getNextElement());
        	jLabel6.setVisible(false);
        }catch(NullPointerException e){
        	jLabel6.setText("no elments");
        	jLabel6.setVisible(true);
        }
        updateFields(temp);
    }                                          

    private void ButtonOpenActionPerformed(java.awt.event.ActionEvent evt) {
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter xmlfilter = new FileNameExtensionFilter( "xml files (*.xml)", "xml");
        chooser.setFileFilter(xmlfilter);
        chooser.setFileFilter(xmlfilter);
        chooser.showOpenDialog(null);
        jLabel6.setVisible(false);
        arrayOfHomeworks = new HomeworksArray();
        try {
         	parce = new XMLParcer(chooser.getSelectedFile().getAbsolutePath());
			arrayOfHomeworks = parce.readFile();
			homeworkName.setText(arrayOfHomeworks.getFirstElement().getTitle());
			task.setText(arrayOfHomeworks.getFirstElement().getTask());
			platform.setText(arrayOfHomeworks.getFirstElement().getPlatform());
			endDate.setText(arrayOfHomeworks.getFirstElement().getEndDate());
			hint.setText(arrayOfHomeworks.getFirstElement().getHint());
		} catch (IOException | JAXBException e) {
			jLabel6.setText("cannot open this file");
			jLabel6.setVisible(true);
		} catch(IndexOutOfBoundsException e){
			jLabel6.setText("wrong file or incorrect file!");
			jLabel6.setVisible(true);
		}
    }

    private void ButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {                                               
    	Homework temp = new Homework();
    	try{
    		temp = new Homework(arrayOfHomeworks.getPreviousElement());
    		jLabel6.setVisible(false);
    	}catch(NullPointerException e){
        	jLabel6.setText("no elments");
        	jLabel6.setVisible(true);
        }
        updateFields(temp);
    }                                              

    private void ButtonDeleteElementActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        try{
        	arrayOfHomeworks.deleteElement();
        	Homework temp = new Homework(arrayOfHomeworks.getNextElement());
        	updateFields(temp);
        	jLabel6.setVisible(false);
        } catch(NullPointerException e){
        	jLabel6.setText("cannot save nothing!");
        	jLabel6.setVisible(true);
        }
    }                                                   

    private void ButtonClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        homeworkName.setText(null);
        task.setText(null);
        platform.setText(null);
        endDate.setText(null);
        hint.setText(null);
    }                                                 

    private void ButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {
    	try{
    		arrayOfHomeworks.addElement(new Homework(homeworkName.getText(), task.getText(), platform.getText(), endDate.getText(), hint.getText()));
    	}catch(NullPointerException e){
    		arrayOfHomeworks = new HomeworksArray(new Homework(homeworkName.getText(), task.getText(), platform.getText(), endDate.getText(), hint.getText()));
    	}
    }                                            

    private void ButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {                                           
        try {
    		parce = new XMLParcer("data\\new" + new Random(System.currentTimeMillis()).nextInt() + ".xml");
            parce.writeToFile(arrayOfHomeworks);
            jLabel6.setVisible(false);
        } catch (JAXBException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
        } catch(NullPointerException e){
        	e.printStackTrace();
        	if(arrayOfHomeworks.getClass() != null){
        		//make field visible!
        	}
        	jLabel6.setText("cannot save nothing!");
        	jLabel6.setVisible(true);
        }
    }                                          

    private void updateFields(Homework temp){
        homeworkName.setText(temp.getTitle());
        task.setText(temp.getTask());
        platform.setText(temp.getPlatform());
        endDate.setText(temp.getEndDate());
        hint.setText(temp.getHint());
    }
    
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ButtonClearFields;
    private javax.swing.JButton ButtonDeleteElement;
    private javax.swing.JButton ButtonNext;
    private javax.swing.JButton ButtonOpen;
    private javax.swing.JButton ButtonPrevious;
    private javax.swing.JButton ButtonSave;
    private javax.swing.JButton ButtonSubmit;
    private javax.swing.JTextField endDate;
    private javax.swing.JTextField hint;
    private javax.swing.JTextField homeworkName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField platform;
    private javax.swing.JTextField task;
    // End of variables declaration                   
}
